// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetGoogleProfileOKCode is the HTTP code returned for type GetGoogleProfileOK
const GetGoogleProfileOKCode int = 200

/*GetGoogleProfileOK Google profile info

swagger:response getGoogleProfileOK
*/
type GetGoogleProfileOK struct {

	/*
	  In: Body
	*/
	Payload *GetGoogleProfileOKBody `json:"body,omitempty"`
}

// NewGetGoogleProfileOK creates GetGoogleProfileOK with default headers values
func NewGetGoogleProfileOK() *GetGoogleProfileOK {

	return &GetGoogleProfileOK{}
}

// WithPayload adds the payload to the get google profile o k response
func (o *GetGoogleProfileOK) WithPayload(payload *GetGoogleProfileOKBody) *GetGoogleProfileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get google profile o k response
func (o *GetGoogleProfileOK) SetPayload(payload *GetGoogleProfileOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGoogleProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGoogleProfileInternalServerErrorCode is the HTTP code returned for type GetGoogleProfileInternalServerError
const GetGoogleProfileInternalServerErrorCode int = 500

/*GetGoogleProfileInternalServerError couldn't process request

swagger:response getGoogleProfileInternalServerError
*/
type GetGoogleProfileInternalServerError struct {
}

// NewGetGoogleProfileInternalServerError creates GetGoogleProfileInternalServerError with default headers values
func NewGetGoogleProfileInternalServerError() *GetGoogleProfileInternalServerError {

	return &GetGoogleProfileInternalServerError{}
}

// WriteResponse to the client
func (o *GetGoogleProfileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
