// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPubKeyHandlerFunc turns a function with the right signature into a get pub key handler
type GetPubKeyHandlerFunc func(GetPubKeyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPubKeyHandlerFunc) Handle(params GetPubKeyParams) middleware.Responder {
	return fn(params)
}

// GetPubKeyHandler interface for that can handle valid get pub key params
type GetPubKeyHandler interface {
	Handle(GetPubKeyParams) middleware.Responder
}

// NewGetPubKey creates a new http.Handler for the get pub key operation
func NewGetPubKey(ctx *middleware.Context, handler GetPubKeyHandler) *GetPubKey {
	return &GetPubKey{Context: ctx, Handler: handler}
}

/* GetPubKey swagger:route GET /pub-key getPubKey

GetPubKey get pub key API

*/
type GetPubKey struct {
	Context *middleware.Context
	Handler GetPubKeyHandler
}

func (o *GetPubKey) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPubKeyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
