// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPubKeyOKCode is the HTTP code returned for type GetPubKeyOK
const GetPubKeyOKCode int = 200

/*GetPubKeyOK Stripe publishable key

swagger:response getPubKeyOK
*/
type GetPubKeyOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetPubKeyOK creates GetPubKeyOK with default headers values
func NewGetPubKeyOK() *GetPubKeyOK {

	return &GetPubKeyOK{}
}

// WithPayload adds the payload to the get pub key o k response
func (o *GetPubKeyOK) WithPayload(payload string) *GetPubKeyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get pub key o k response
func (o *GetPubKeyOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPubKeyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
