// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUserCreditOKCode is the HTTP code returned for type GetUserCreditOK
const GetUserCreditOKCode int = 200

/*GetUserCreditOK User credit info

swagger:response getUserCreditOK
*/
type GetUserCreditOK struct {

	/*
	  In: Body
	*/
	Payload *GetUserCreditOKBody `json:"body,omitempty"`
}

// NewGetUserCreditOK creates GetUserCreditOK with default headers values
func NewGetUserCreditOK() *GetUserCreditOK {

	return &GetUserCreditOK{}
}

// WithPayload adds the payload to the get user credit o k response
func (o *GetUserCreditOK) WithPayload(payload *GetUserCreditOKBody) *GetUserCreditOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user credit o k response
func (o *GetUserCreditOK) SetPayload(payload *GetUserCreditOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserCreditOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserCreditInternalServerErrorCode is the HTTP code returned for type GetUserCreditInternalServerError
const GetUserCreditInternalServerErrorCode int = 500

/*GetUserCreditInternalServerError couldn't process request

swagger:response getUserCreditInternalServerError
*/
type GetUserCreditInternalServerError struct {
}

// NewGetUserCreditInternalServerError creates GetUserCreditInternalServerError with default headers values
func NewGetUserCreditInternalServerError() *GetUserCreditInternalServerError {

	return &GetUserCreditInternalServerError{}
}

// WriteResponse to the client
func (o *GetUserCreditInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
