// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetImagesPagesOKCode is the HTTP code returned for type GetImagesPagesOK
const GetImagesPagesOKCode int = 200

/*GetImagesPagesOK Number of images count

swagger:response getImagesPagesOK
*/
type GetImagesPagesOK struct {

	/*
	  In: Body
	*/
	Payload int64 `json:"body,omitempty"`
}

// NewGetImagesPagesOK creates GetImagesPagesOK with default headers values
func NewGetImagesPagesOK() *GetImagesPagesOK {

	return &GetImagesPagesOK{}
}

// WithPayload adds the payload to the get images pages o k response
func (o *GetImagesPagesOK) WithPayload(payload int64) *GetImagesPagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get images pages o k response
func (o *GetImagesPagesOK) SetPayload(payload int64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImagesPagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetImagesPagesInternalServerErrorCode is the HTTP code returned for type GetImagesPagesInternalServerError
const GetImagesPagesInternalServerErrorCode int = 500

/*GetImagesPagesInternalServerError couldn't process request

swagger:response getImagesPagesInternalServerError
*/
type GetImagesPagesInternalServerError struct {
}

// NewGetImagesPagesInternalServerError creates GetImagesPagesInternalServerError with default headers values
func NewGetImagesPagesInternalServerError() *GetImagesPagesInternalServerError {

	return &GetImagesPagesInternalServerError{}
}

// WriteResponse to the client
func (o *GetImagesPagesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
