// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"th3-sh0p-api/models"
)

// GetImagesOKCode is the HTTP code returned for type GetImagesOK
const GetImagesOKCode int = 200

/*GetImagesOK Images to show

swagger:response getImagesOK
*/
type GetImagesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Image `json:"body,omitempty"`
}

// NewGetImagesOK creates GetImagesOK with default headers values
func NewGetImagesOK() *GetImagesOK {

	return &GetImagesOK{}
}

// WithPayload adds the payload to the get images o k response
func (o *GetImagesOK) WithPayload(payload []*models.Image) *GetImagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get images o k response
func (o *GetImagesOK) SetPayload(payload []*models.Image) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Image, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetImagesInternalServerErrorCode is the HTTP code returned for type GetImagesInternalServerError
const GetImagesInternalServerErrorCode int = 500

/*GetImagesInternalServerError couldn't process request

swagger:response getImagesInternalServerError
*/
type GetImagesInternalServerError struct {
}

// NewGetImagesInternalServerError creates GetImagesInternalServerError with default headers values
func NewGetImagesInternalServerError() *GetImagesInternalServerError {

	return &GetImagesInternalServerError{}
}

// WriteResponse to the client
func (o *GetImagesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
