// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostImagePackOKCode is the HTTP code returned for type PostImagePackOK
const PostImagePackOKCode int = 200

/*PostImagePackOK Payment intent

swagger:response postImagePackOK
*/
type PostImagePackOK struct {

	/*
	  In: Body
	*/
	Payload *PostImagePackOKBody `json:"body,omitempty"`
}

// NewPostImagePackOK creates PostImagePackOK with default headers values
func NewPostImagePackOK() *PostImagePackOK {

	return &PostImagePackOK{}
}

// WithPayload adds the payload to the post image pack o k response
func (o *PostImagePackOK) WithPayload(payload *PostImagePackOKBody) *PostImagePackOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post image pack o k response
func (o *PostImagePackOK) SetPayload(payload *PostImagePackOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostImagePackOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostImagePackBadRequestCode is the HTTP code returned for type PostImagePackBadRequest
const PostImagePackBadRequestCode int = 400

/*PostImagePackBadRequest openAI returned a non 200

swagger:response postImagePackBadRequest
*/
type PostImagePackBadRequest struct {
}

// NewPostImagePackBadRequest creates PostImagePackBadRequest with default headers values
func NewPostImagePackBadRequest() *PostImagePackBadRequest {

	return &PostImagePackBadRequest{}
}

// WriteResponse to the client
func (o *PostImagePackBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostImagePackInternalServerErrorCode is the HTTP code returned for type PostImagePackInternalServerError
const PostImagePackInternalServerErrorCode int = 500

/*PostImagePackInternalServerError couldn't process request

swagger:response postImagePackInternalServerError
*/
type PostImagePackInternalServerError struct {
}

// NewPostImagePackInternalServerError creates PostImagePackInternalServerError with default headers values
func NewPostImagePackInternalServerError() *PostImagePackInternalServerError {

	return &PostImagePackInternalServerError{}
}

// WriteResponse to the client
func (o *PostImagePackInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
