// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostImagesOKCode is the HTTP code returned for type PostImagesOK
const PostImagesOKCode int = 200

/*PostImagesOK Images to show

swagger:response postImagesOK
*/
type PostImagesOK struct {

	/*
	  In: Body
	*/
	Payload *PostImagesOKBody `json:"body,omitempty"`
}

// NewPostImagesOK creates PostImagesOK with default headers values
func NewPostImagesOK() *PostImagesOK {

	return &PostImagesOK{}
}

// WithPayload adds the payload to the post images o k response
func (o *PostImagesOK) WithPayload(payload *PostImagesOKBody) *PostImagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post images o k response
func (o *PostImagesOK) SetPayload(payload *PostImagesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostImagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
