// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Th3-Sh0p API
//
//  API description in Markdown.
//  Schemes:
//    http
//  Host: ai.th3-sh0p.com
//  BasePath: /v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
